# Generated by Django 6.0.1 on 2026-01-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Immatriculation')),
                ('brand', models.CharField(max_length=50, verbose_name='Marque')),
                ('model', models.CharField(max_length=50, verbose_name='Modèle')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('IN_USE', 'En utilisation'), ('MAINTENANCE', 'En maintenance'), ('UNAVAILABLE', 'Indisponible')], default='AVAILABLE', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cars',
                'ordering': ['-created_at'],
            },
        ),
    ]
